# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  HTMLCHECK:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt update && sudo apt upgrade -y
    - run: sudo sed -i 's/focal/devel/g' /etc/apt/sources.list
    - run: sudo apt update && sudo apt upgrade -y
    - run: sudo apt --with-new-pkgs upgrade -y
    - run: sudo apt autoremove && sudo apt autoclean
    - run: lsb_release -a
    - run: uname -a
    - uses: actions/checkout@v3
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
          root: ./
          log_level: INFO
          css: true
    - uses: actions/upload-artifact@v3
      with:
          name: log
          path: log.log
